VERSION ?= $(shell poetry run python -c "from setuptools_scm import get_version;print(get_version())")
OPENAPIGEN_IMAGE ?= openapitools/openapi-generator-cli:v7.5.0

clean:
	rm -rf api
	rm openapi.yaml

api: patched_openapi.yaml
	docker run --rm --user `id -u`:`id -g` -v ${PWD}:/local ${OPENAPIGEN_IMAGE} \
	           generate -i /local/openapi.yaml \
	           --git-user-id rienafairefr \
	           --git-repo-id ynab \
	           -g python -o /local/api \
	           --additional-properties projectName=pyynab --package-name ynab \
	           --additional-properties packageVersion="$(VERSION)" \
	           --additional-properties appDescription="pyynab, an autogenerated package to access public API of app.ynab.com" \
	           --additional-properties appName="ynab" \
	           --additional-properties infoEmail="cheery.iron6016@fastmail.com"

patched_openapi.yaml: openapi.yaml
	python3 patch_openapi.py
